name: unity_mediation
description: Unity Mediation plugin for Flutter Applications. This plugin is able to display Rewarded and Interstitial Ads from different ad sources.
version: 0.1.0
homepage: https://github.com/pavelzaichyk/flutter_unity_mediation
repository: https://github.com/pavelzaichyk/flutter_unity_mediation
funding:
  - https://paypal.me/pavelzaichyk
  - https://buymeacoffee.com/rebeloid
  - https://paypal.com/donate/?hosted_button_id=EG9DHRCSB5MY4

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.rebeloid.unity_mediation
        pluginClass: UnityMediationPlugin
      ios:
        pluginClass: UnityMediationPlugin
